### ISSUE TITLE
[Frontend] Todo 페이지 개발 및 구현

### ISSUE THREAD

**Issue by ezurno** [we-exercise-efficiently/wee-frontend#11]
- [x] Todo 페이지 와이어 프레임 구현
  - [x] 루틴 리스트
  - [x] 이미지 영역
  - [x] 달력 기능
- [x] Todo 페이지 1차 디자인 적용
- [ ] 데이터 연결
  - [ ] API 연결
    - [ ] 사용자 정보 불러오기
    - [ ] 사용자 정보 수정
  - [ ] Error Handling
- [ ] 기능 구현
  - [ ] 이미지 저장
  - [ ] 루틴 공유
